# thinker_tools.py
# PM Tool - Denker Tool-Funktionen
# Path: C:\Users\USass\Billi_Bilder\agent\

import os
import re
from datetime import datetime

MEMORY_PATH = r"C:\Users\USass\Billi_Bilder\SHARED_BRAIN\MEMORY.md"
SOLUTIONS_PATH = r"C:\Users\USass\Billi_Bilder\SHARED_BRAIN\SOLUTIONS.md"
RULES_PATH = r"C:\Users\USass\Billi_Bilder\SHARED_BRAIN\RULES.md"

OK = "[OK]"
WARN = "[WARN]"
ERROR = "[ERROR]"


def read_memory() -> dict:
    """Liest die neuesten Waechter-Reports aus MEMORY.md"""
    result = {
        "status": ERROR,
        "reports": [],
        "errors": [],
        "warnings": [],
        "last_check": None,
    }

    if not os.path.exists(MEMORY_PATH):
        print(f"  {ERROR} MEMORY.md nicht gefunden")
        return result

    try:
        with open(MEMORY_PATH, "r", encoding="utf-8") as f:
            content = f.read()

        # Alle Reports extrahieren
        report_blocks = re.split(r"## WÄCHTER-REPORT|## WAECHTER-REPORT", content)

        for block in report_blocks[1:]:  # Erster Block ist Header
            if block.strip():
                # Zeitstempel finden
                ts_match = re.search(r"\[(\d{2}\.\d{2}\.\d{4} \d{2}:\d{2})\]", block)
                timestamp = ts_match.group(1) if ts_match else "Unbekannt"

                # Fehler extrahieren
                error_lines = re.findall(r"\s*-\s*[✗xX]\s*(.+)", block)
                for e in error_lines:
                    result["errors"].append({"time": timestamp, "detail": e.strip()})

                # Warnungen extrahieren
                warn_lines = re.findall(r"\s*-\s*⚠\s*(.+)", block)
                for w in warn_lines:
                    result["warnings"].append({"time": timestamp, "detail": w.strip()})

                result["reports"].append(
                    {"timestamp": timestamp, "block": block.strip()[:200]}
                )

        result["status"] = OK if result["reports"] else WARN
        result["last_check"] = datetime.now().strftime("%d.%m.%Y %H:%M")

        print(f"  {OK} MEMORY.md gelesen")
        print(f"    - Reports: {len(result['reports'])}")
        print(f"    - Fehler: {len(result['errors'])}")
        print(f"    - Warnungen: {len(result['warnings'])}")

    except Exception as e:
        print(f"  {ERROR} MEMORY.md Lesefehler: {e}")

    return result


def load_rules() -> str:
    """Laedt RULES.md fuer Ollama-Prompt"""
    if not os.path.exists(RULES_PATH):
        return "RULES.md nicht gefunden"

    try:
        with open(RULES_PATH, "r", encoding="utf-8") as f:
            return f.read()[:3000]  # Erste 3000 Zeichen
    except:
        return "Fehler beim Laden"


def write_solutions(solutions: list) -> bool:
    """Schreibt Loesungsvorschlaege in SOLUTIONS.md"""
    timestamp = datetime.now().strftime("%d.%m.%Y %H:%M")

    header = f"""
# SOLUTIONS.md — Denker Report
Generiert: {timestamp}
Agent: Denker (Stage 2)

---

"""

    content = header

    if not solutions:
        content += "## Keine Loesungen erforderlich\n\n"
        content += "Alle Systeme funktionieren normaal.\n"
    else:
        content += f"## {len(solutions)} Loesungsvorschlaege\n\n"

        for i, sol in enumerate(solutions, 1):
            content += f"### {i}. {sol.get('title', 'Ohne Titel')}\n"
            content += f"- **Problem:** {sol.get('problem', '-')}\n"
            content += f"- **Loesung:** {sol.get('solution', '-')}\n"
            content += f"- **Prioritaet:** {sol.get('priority', 'MITTEL')}\n"
            content += f"- **Verantwortlich:** {sol.get('owner', 'TBD')}\n\n"

    content += "---\n*Generated by Denker (Stage 2) - Ollama Agent*\n"

    try:
        with open(SOLUTIONS_PATH, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  {OK} SOLUTIONS.md geschrieben")
        return True
    except Exception as e:
        print(f"  {ERROR} SOLUTIONS.md Fehler: {e}")
        return False


def build_analysis_prompt(memory_data: dict, rules: str) -> str:
    """Baut den Ollama-Prompt fuer Fehleranalyse"""

    errors_text = "\n".join(
        [f"- {e['detail']} ({e['time']})" for e in memory_data.get("errors", [])]
    )
    warnings_text = "\n".join(
        [f"- {w['detail']} ({w['time']})" for w in memory_data.get("warnings", [])]
    )

    prompt = f"""Du bist ein Problemanalyst.

## Deine Aufgabe
Analysiere die folgenden Fehler und Warnungen aus dem Waechter-System und schlage konkrete Loesungen vor.

## Kontext (aus RULES.md)
{rules}

## Gefundene Fehler
{errors_text if errors_text else "Keine Fehler"}

## Gefundene Warnungen
{warnings_text if warnings_text else "Keine Warnungen"}

## Deine Antwort
Antworte im JSON-Format:
{{
  "solutions": [
    {{
      "title": "Kurzer Titel fuer die Loesung",
      "problem": "Beschreibung des Problems",
      "solution": "Konkrete Loesungsschritte",
      "priority": "HOCH/MITTEL/NIEDRIG",
      "owner": "Wer sollte das umsetzen"
    }}
  ]
}}

Wichtig:
- Sei konkret und praezise
- Priorisiere nach Kritikalitaet
- Wenn alles OK ist, antworte mit leerem solutions-Array
"""

    return prompt


def prepare_handover(solutions: list) -> str:
    """Bereitet Uebergabe an Stage 3 (Ausfuehrer) vor"""

    if not solutions:
        return "KEINE AKTION ERFORDERLICH - Alle Systeme funktionieren."

    handover = "## UEBERGABE AN AUSFUEHRER (Stage 3)\n\n"
    handover += f"**Anzahl Loesungen:** {len(solutions)}\n\n"

    for i, sol in enumerate(solutions[:3], 1):  # Max 3 fuer Uebergabe
        handover += f"### AUFGABE {i}\n"
        handover += f"- **Was:** {sol.get('title', '-')}\n"
        handover += f"- **Warum:** {sol.get('problem', '-')}\n"
        handover += f"- **Wie:** {sol.get('solution', '-')}\n\n"

    return handover
